services:
  - type: web
    name: vpco
    env: node
   plan: free
   region: oregon
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
   healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DOMAIN_NAME
        value: vigliottaproperties.com
      - key: WIX_API_KEY
        sync: false
      - key: WIX_API_TOKEN
        sync: false
      - key: WIX_SITE_ID
        sync: false
      - key: WIX_ACCOUNT_ID
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: SLACK_APP_ID
        sync: false
      - key: SLACK_CLIENT_ID
        sync: false
      - key: SLACK_CLIENT_SECRET
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: SLACK_VERIFICATION_TOKEN
        sync: false
