name: CI

on:
  push:
    branches: [ main, mainVPCO ]
  pull_request:
    branches: [ main, mainVPCO ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci || npm install
      - name: Run tests
        run: npm test