name: CI & Deploy

on:
  push:
    branches: [ main, mainVPCO ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci || npm install
      - name: Run tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/mainVPCO'
    steps:
      - name: Trigger Render deploy hook
        if: ${{ secrets.RENDER_DEPLOY_HOOK_URL != '' }}
        run: |
          curl -fsSL -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" -o /dev/null
      - name: Wait for deployment (optional health check)
        if: ${{ secrets.RENDER_HEALTHCHECK_URL != '' }}
        run: |
          echo "Waiting for deployment to become healthy..."
          for i in {1..30}; do
            STATUS=$(curl -fsS --max-time 5 "${{ secrets.RENDER_HEALTHCHECK_URL }}" || true)
            if echo "$STATUS" | grep -q '"status":"ok"'; then
              echo "Service healthy"; exit 0;
            fi
            echo "Attempt $i/30: not healthy yet"; sleep 10;
          done
          echo "Health check failed"; exit 1